name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: stable
          cache: true

      - name: Backup AndroidManifest
        run: |
          cp android/app/src/main/AndroidManifest.xml /tmp/AndroidManifest.xml

      - name: Generate Android Project
        run: |
          flutter create --platforms=android .
          rm -rf test

      - name: Restore AndroidManifest
        run: |
          cp /tmp/AndroidManifest.xml android/app/src/main/AndroidManifest.xml

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Analyze
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK
        run: |
          mkdir -p output
          cp build/app/outputs/flutter-apk/app-release.apk output/ESP32_Motor_Control.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ESP32-Motor-Control-APK
          path: output/ESP32_Motor_Control.apk
